version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLIENT_TOKEN=${CLIENT_TOKEN}
      - CLIENT_OWNER=${CLIENT_OWNER}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=${DATABASE_URL}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      - 'postgres'
