FROM node:lts-alpine

WORKDIR /lumafly

COPY ../.. .

RUN yarn set version berry

RUN yarn install

ENTRYPOINT [ "npx", "nodemon", "-e", "ts", "-w", "/lumafly/packages/core", "-x", "yarn workspace @lumafly/core start" ]