version: '3'
services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    environment:
      - TOKEN=${DISCORD_BOT_TOKEN}
      - OWNER=${DISCORD_BOT_OWNER}
      - PREFIX=${DISCORD_BOT_PREFIX}
    network_mode: host