version: '3'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=$LUMAFLY_DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - .pgdata:/var/lib/postgresql/data
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    network_mode: host
    depends_on:
      - 'db'
