version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: dbPassword
    ports:
      - '5432:5432'
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLIENT_TOKEN=${CLIENT_TOKEN}
      - CLIENT_OWNER=${CLIENT_OWNER}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - DATABASE_URL=postgresql://postgres:dbPassword@postgres:5432/mydb?schema=public
    depends_on:
      - 'postgres'
