# fly.toml file generated for lumafly on 2022-09-11T10:35:01+08:00

app = "lumafly"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
