# fly.toml file generated for lumafly on 2022-06-26T09:57:04+08:00

app = "lumafly"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[deploy]
  release_command = "node main.js --deploy"