on: push
name: Check if files are formatted.

jobs:
  skip-check:
    name: Skip Check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          paths: '["src/**/*.ts", ".github/workflows/format-check.yml"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          cancel_others: "true"

  format-check:
    name: Formatting check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: "yarn"
      - name: Install packages and run format check
        run: yarn install

      - name: Run formatting check
        run: yarn format:check
