on: push
name: Check if files are formatted.

jobs:
  skip-check:
    name: Skip Check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths: '["src/**/*.ts", ".github/workflows/format-check.yml"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
          cancel_others: 'true'

  format-check:
    name: Formatting check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'
      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Run formatting check
        run: bun format:check
