name: Run tests

on: push

env:
  NODE_VERSION: 16.13.2
  CLIENT_OWNER: ${{ secrets.CLIENT_OWNER }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
      - name: Install packages and run tests
        run: |
          yarn install
          yarn test
